export type Json =
  | { [key: string]: Json | undefined }
  | Json[]
  | string
  | number
  | boolean
  | null

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface Database {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string
          user_id: string
          display_name: string
          email: string | null
          phone: string | null
          wallet_address: string | null
          avatar_url: string | null
          bio: string | null
          university: string | null
          major: string | null
          graduation_year: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          display_name: string
          email?: string | null
          phone?: string | null
          wallet_address?: string | null
          avatar_url?: string | null
          bio?: string | null
          university?: string | null
          major?: string | null
          graduation_year?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          display_name?: string
          email?: string | null
          phone?: string | null
          wallet_address?: string | null
          avatar_url?: string | null
          bio?: string | null
          university?: string | null
          major?: string | null
          graduation_year?: number | null
          created_at?: string
          updated_at?: string
        }
      }
      user_stats: {
        Row: {
          id: string
          user_id: string
          total_points: number
          total_cashback: number
          level: number
          completed_lessons: number
          portfolio_value: number
          streak_days: number
          last_activity: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          total_points?: number
          total_cashback?: number
          level?: number
          completed_lessons?: number
          portfolio_value?: number
          streak_days?: number
          last_activity?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          total_points?: number
          total_cashback?: number
          level?: number
          completed_lessons?: number
          portfolio_value?: number
          streak_days?: number
          last_activity?: string
          created_at?: string
          updated_at?: string
        }
      }
      ai_chat_sessions: {
        Row: {
          id: string
          user_id: string
          title: string
          subject: string | null
          difficulty_level: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          subject?: string | null
          difficulty_level?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          subject?: string | null
          difficulty_level?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      ai_chat_messages: {
        Row: {
          id: string
          session_id: string
          user_id: string
          role: string
          content: string
          metadata: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          session_id: string
          user_id: string
          role: string
          content: string
          metadata?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          session_id?: string
          user_id?: string
          role?: string
          content?: string
          metadata?: Json | null
          created_at?: string
        }
      }
      campus_store_products: {
        Row: {
          id: string
          name: string
          description: string
          price: number
          category: string
          image_url: string | null
          stock_quantity: number
          is_active: boolean
          university: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          description: string
          price: number
          category: string
          image_url?: string | null
          stock_quantity?: number
          is_active?: boolean
          university?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string
          price?: number
          category?: string
          image_url?: string | null
          stock_quantity?: number
          is_active?: boolean
          university?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      marketplace_listings: {
        Row: {
          id: string
          seller_id: string
          title: string
          description: string
          price: number
          category: string
          condition: string
          location: string | null
          is_active: boolean
          is_sold: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          seller_id: string
          title: string
          description: string
          price: number
          category: string
          condition: string
          location?: string | null
          is_active?: boolean
          is_sold?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          seller_id?: string
          title?: string
          description?: string
          price?: number
          category?: string
          condition?: string
          location?: string | null
          is_active?: boolean
          is_sold?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      transactions: {
        Row: {
          id: string
          user_id: string
          type: string
          amount: number
          currency: string
          description: string
          reference_id: string | null
          status: string
          metadata: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: string
          amount: number
          currency?: string
          description: string
          reference_id?: string | null
          status?: string
          metadata?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          type?: string
          amount?: number
          currency?: string
          description?: string
          reference_id?: string | null
          status?: string
          metadata?: Json | null
          created_at?: string
          updated_at?: string
        }
      }
      user_preferences: {
        Row: {
          id: string
          user_id: string
          notifications_enabled: boolean
          email_notifications: boolean
          push_notifications: boolean
          theme: 'light' | 'dark' | 'system'
          language: string
          timezone: string
          privacy_settings: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          notifications_enabled?: boolean
          email_notifications?: boolean
          push_notifications?: boolean
          theme?: 'light' | 'dark' | 'system'
          language?: string
          timezone?: string
          privacy_settings?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          notifications_enabled?: boolean
          email_notifications?: boolean
          push_notifications?: boolean
          theme?: 'light' | 'dark' | 'system'
          language?: string
          timezone?: string
          privacy_settings?: Json
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}